### ISSUE TITLE
Not working behind Nginx

### ISSUE THREAD

**Issue by elie222** [dferber90/meteor-prerender#18] opened 2016-03-01 23:51 UTC
I'm running two apps from the code base at two different urls.

One of the apps works fine with this package and all is in order when I go to: https://prerender.io/crawl-stats.

The second app doesn't work however and I see the following at https://prerender.io/crawl-stats:
`http://myapp/post/abc` (which obviously causes an error).

The root url should is `https://myapp.com/` so I'm expecting to see `https://somewebsite.com/post/abc` on the crawl-stats page.

The difference between the two sites is that one is behind an nginx (used for ssl and as a load balancer). `myapp` is the appName I gave in my mup.json file (deploying with Meteor Up).

Do you have any idea why these issues are being caused? And I do have to stick the prerender.io stuff in my nginx config file instead to make this work?

**Comment by elie222** [comment] 2016-03-02 00:06
My nginx file looks something like this:

```
upstream myAppName {
  ip_hash;               # for sticky sessions, more below
  server 123.45.678.901:3000;  # server 1
  server 333.22.444.555:3000;  # server 2
}

server {
  listen 80;
  server_name www.myapp.com
  # and all other "server" directives

  location / {
    # the "hostname" below must be same myAppName from upstream directive above
    proxy_pass http://myAppName/;
    # and all other "location" directives
  }
}
```

`proxy_pass http://myAppName/`must be what's causing the errors. Would changing `myAppName` to `somewebsite.com` fix this? And do I need to worry about it not being https then?

**Comment by dferber90** [comment] 2016-03-02 08:24
Oh, that's annoying.

This doesn't seem to be caused by `meteor-prerender`, but seems to be a general problem of prerenderio/nginx. So this is the wrong place to ask for help.

Maybe this helps: https://gist.github.com/thoop/8165802 ?

I'm closing this as it's not related to `meteor-prerender`. If you find a solution, please post/link it here as well for others to see.

**Closed as completed by dferber90** 2016-03-02 08:24 UTC

**Comment by elie222** [comment] 2016-03-02 08:52
Sure
